//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Domain
{
    public Domain()
    {
        this.Domains1 = new HashSet<Domain>();
        this.DomainsWeights = new HashSet<DomainsWeight>();
        this.Questions = new HashSet<Question>();
    }

    public int Id { get; set; }
    public string Name { get; set; }
    public Nullable<int> MasterDomain { get; set; }

    public virtual ICollection<Domain> Domains1 { get; set; }
    public virtual Domain Domain1 { get; set; }
    public virtual ICollection<DomainsWeight> DomainsWeights { get; set; }
    public virtual ICollection<Question> Questions { get; set; }
}

public partial class DomainsWeight
{
    public int User { get; set; }
    public int Domain { get; set; }
    public float Weight { get; set; }

    public virtual Domain Domain1 { get; set; }
    public virtual User User1 { get; set; }
}

public partial class Question
{
    public Question()
    {
        this.QuestionsWeights = new HashSet<QuestionsWeight>();
    }

    public int Id { get; set; }
    public string Question1 { get; set; }
    public string Answer { get; set; }
    public int Domain { get; set; }

    public virtual Domain Domain1 { get; set; }
    public virtual ICollection<QuestionsWeight> QuestionsWeights { get; set; }
}

public partial class QuestionsWeight
{
    public int User { get; set; }
    public int Question { get; set; }
    public float Weight { get; set; }

    public virtual Question Question1 { get; set; }
    public virtual User User1 { get; set; }
}

public partial class User
{
    public User()
    {
        this.DomainsWeights = new HashSet<DomainsWeight>();
        this.QuestionsWeights = new HashSet<QuestionsWeight>();
    }

    public int Id { get; set; }
    public string UserName { get; set; }
    public string Email { get; set; }
    public string Passwrod { get; set; }
    public bool Admin { get; set; }
    public string Confirmed { get; set; }
    public int Note { get; set; }

    public virtual ICollection<DomainsWeight> DomainsWeights { get; set; }
    public virtual ICollection<QuestionsWeight> QuestionsWeights { get; set; }
}
